AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Dynamo Table

Resources:
  AggregateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: bid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: bid
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-Aggregate
Outputs:
  TableName:
    Description: Aggregate Table name
    Value: !Ref AggregateTable
  TableArn:
    Description: Aggregate Table arn
    Value: !GetAtt AggregateTable.Arn
  StreamArn:
    Description: Aggregate Table Stream arn
    Value: !GetAtt AggregateTable.StreamArn
